# Generated by Django 4.2.23 on 2025-06-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('msp', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã sản phẩm')),
                ('tensp', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('gia', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá')),
                ('mota', models.TextField(verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
    ]
